apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-consumer
  namespace: default
spec:
  replicas: 0                    # start with 0; KEDA will scale to >0 when queue has messages
  selector:
    matchLabels:
      app: rabbit-consumer
  template:
    metadata:
      labels:
        app: rabbit-consumer
    spec:
      containers:
      - name: consumer
        image: "<REGISTRY/IMAGE-or-kedacore/tests-rabbitmq:latest>"
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq.messaging.svc.cluster.local:5672/"
        # app should consume one message at a time to demo scaling; adjust if needed
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
